// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using padrao.Data;

#nullable disable

namespace padrao.Migrations.CustoDB
{
    [DbContext(typeof(CustoDBContext))]
    partial class CustoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("padrao.Models.CustoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cc")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("cif")
                        .HasColumnType("integer");

                    b.Property<int>("cpp")
                        .HasColumnType("integer");

                    b.Property<string>("exercicio")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("md")
                        .HasColumnType("integer");

                    b.Property<int>("mod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Custo");
                });
#pragma warning restore 612, 618
        }
    }
}
