// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using padrao.Data;

#nullable disable

namespace padrao.Migrations.ImpostosDBContexMigrations
{
    [DbContext(typeof(ImpostosDBContex))]
    [Migration("20230302013112_secondMigartion")]
    partial class secondMigartion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("padrao.Models.ImpModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("cofins")
                        .HasMaxLength(70)
                        .HasColumnType("integer");

                    b.Property<string>("exercicio")
                        .HasColumnType("text");

                    b.Property<int>("pis")
                        .HasMaxLength(70)
                        .HasColumnType("integer");

                    b.Property<int>("rbruta")
                        .HasMaxLength(70)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Imp");
                });
#pragma warning restore 612, 618
        }
    }
}
